name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Build
        run: scripts/build.sh
      - name: Test with the Go CLI
        run: scripts/test.sh
      - name: Run govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@v1.2.0 ./...
