on:
  release:
    types: [created]

name: Create and Upload Release Artifact

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-20.04
    steps:
      - name: Get the release version
        id: get_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Build
        run: scripts/build.sh
      - name: Test
        run: scripts/test.sh
      - name: Package the Release Artifacts
        run: tar -zcf openidprovider-${{ env.RELEASE_VERSION }}-linux-x86.tar.gz -C bin createuser createkey server
      - name: Upload the Artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'openidprovider-*'
